// Package peparser provides parsing functionality for Windows PE (Portable Executable) files.
package peparser

// DOS/PE Magic values
const (
	DOSMagic = 0x5A4D     // "MZ"
	PEMagic  = 0x00004550 // "PE\0\0"
)

// Optional Header Magic values
const (
	PE32Magic  = 0x10B // PE32 (32-bit)
	PE32PMagic = 0x20B // PE32+ (64-bit)
)

// Machine Types (IMAGE_FILE_MACHINE_*)
const (
	IMAGE_FILE_MACHINE_UNKNOWN     = 0x0
	IMAGE_FILE_MACHINE_ALPHA       = 0x184
	IMAGE_FILE_MACHINE_ALPHA64     = 0x284
	IMAGE_FILE_MACHINE_AM33        = 0x1d3
	IMAGE_FILE_MACHINE_AMD64       = 0x8664
	IMAGE_FILE_MACHINE_ARM         = 0x1c0
	IMAGE_FILE_MACHINE_ARM64       = 0xaa64
	IMAGE_FILE_MACHINE_ARM64EC     = 0xa641
	IMAGE_FILE_MACHINE_ARM64X      = 0xa64e
	IMAGE_FILE_MACHINE_ARMNT       = 0x1c4
	IMAGE_FILE_MACHINE_AXP64       = 0x284
	IMAGE_FILE_MACHINE_EBC         = 0xebc
	IMAGE_FILE_MACHINE_I386        = 0x14c
	IMAGE_FILE_MACHINE_IA64        = 0x200
	IMAGE_FILE_MACHINE_LOONGARCH32 = 0x6232
	IMAGE_FILE_MACHINE_LOONGARCH64 = 0x6264
	IMAGE_FILE_MACHINE_M32R        = 0x9041
	IMAGE_FILE_MACHINE_MIPS16      = 0x266
	IMAGE_FILE_MACHINE_MIPSFPU     = 0x366
	IMAGE_FILE_MACHINE_MIPSFPU16   = 0x466
	IMAGE_FILE_MACHINE_POWERPC     = 0x1f0
	IMAGE_FILE_MACHINE_POWERPCFP   = 0x1f1
	IMAGE_FILE_MACHINE_R3000       = 0x162
	IMAGE_FILE_MACHINE_R3000BE     = 0x160
	IMAGE_FILE_MACHINE_R4000       = 0x166
	IMAGE_FILE_MACHINE_R10000      = 0x168
	IMAGE_FILE_MACHINE_RISCV32     = 0x5032
	IMAGE_FILE_MACHINE_RISCV64     = 0x5064
	IMAGE_FILE_MACHINE_RISCV128    = 0x5128
	IMAGE_FILE_MACHINE_SH3         = 0x1a2
	IMAGE_FILE_MACHINE_SH3DSP      = 0x1a3
	IMAGE_FILE_MACHINE_SH4         = 0x1a6
	IMAGE_FILE_MACHINE_SH5         = 0x1a8
	IMAGE_FILE_MACHINE_THUMB       = 0x1c2
	IMAGE_FILE_MACHINE_WCEMIPSV2   = 0x169
)

// File Characteristics (IMAGE_FILE_*)
const (
	IMAGE_FILE_RELOCS_STRIPPED         = 0x0001
	IMAGE_FILE_EXECUTABLE_IMAGE        = 0x0002
	IMAGE_FILE_LINE_NUMS_STRIPPED      = 0x0004
	IMAGE_FILE_LOCAL_SYMS_STRIPPED     = 0x0008
	IMAGE_FILE_AGGRESSIVE_WS_TRIM      = 0x0010
	IMAGE_FILE_LARGE_ADDRESS_AWARE     = 0x0020
	IMAGE_FILE_BYTES_REVERSED_LO       = 0x0080
	IMAGE_FILE_32BIT_MACHINE           = 0x0100
	IMAGE_FILE_DEBUG_STRIPPED          = 0x0200
	IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP = 0x0400
	IMAGE_FILE_NET_RUN_FROM_SWAP       = 0x0800
	IMAGE_FILE_SYSTEM                  = 0x1000
	IMAGE_FILE_DLL                     = 0x2000
	IMAGE_FILE_UP_SYSTEM_ONLY          = 0x4000
	IMAGE_FILE_BYTES_REVERSED_HI       = 0x8000
)

// Windows Subsystem values (IMAGE_SUBSYSTEM_*)
const (
	IMAGE_SUBSYSTEM_UNKNOWN                  = 0
	IMAGE_SUBSYSTEM_NATIVE                   = 1
	IMAGE_SUBSYSTEM_WINDOWS_GUI              = 2
	IMAGE_SUBSYSTEM_WINDOWS_CUI              = 3
	IMAGE_SUBSYSTEM_OS2_CUI                  = 5
	IMAGE_SUBSYSTEM_POSIX_CUI                = 7
	IMAGE_SUBSYSTEM_NATIVE_WINDOWS           = 8
	IMAGE_SUBSYSTEM_WINDOWS_CE_GUI           = 9
	IMAGE_SUBSYSTEM_EFI_APPLICATION          = 10
	IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER  = 11
	IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER       = 12
	IMAGE_SUBSYSTEM_EFI_ROM                  = 13
	IMAGE_SUBSYSTEM_XBOX                     = 14
	IMAGE_SUBSYSTEM_WINDOWS_BOOT_APPLICATION = 16
)

// DLL Characteristics (IMAGE_DLLCHARACTERISTICS_*)
const (
	IMAGE_DLLCHARACTERISTICS_HIGH_ENTROPY_VA       = 0x0020
	IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE          = 0x0040
	IMAGE_DLLCHARACTERISTICS_FORCE_INTEGRITY       = 0x0080
	IMAGE_DLLCHARACTERISTICS_NX_COMPAT             = 0x0100
	IMAGE_DLLCHARACTERISTICS_NO_ISOLATION          = 0x0200
	IMAGE_DLLCHARACTERISTICS_NO_SEH                = 0x0400
	IMAGE_DLLCHARACTERISTICS_NO_BIND               = 0x0800
	IMAGE_DLLCHARACTERISTICS_APPCONTAINER          = 0x1000
	IMAGE_DLLCHARACTERISTICS_WDM_DRIVER            = 0x2000
	IMAGE_DLLCHARACTERISTICS_GUARD_CF              = 0x4000
	IMAGE_DLLCHARACTERISTICS_TERMINAL_SERVER_AWARE = 0x8000
)

// Data Directory Indices (IMAGE_DIRECTORY_ENTRY_*)
const (
	IMAGE_DIRECTORY_ENTRY_EXPORT         = 0  // Export Table
	IMAGE_DIRECTORY_ENTRY_IMPORT         = 1  // Import Table
	IMAGE_DIRECTORY_ENTRY_RESOURCE       = 2  // Resource Table
	IMAGE_DIRECTORY_ENTRY_EXCEPTION      = 3  // Exception Table
	IMAGE_DIRECTORY_ENTRY_SECURITY       = 4  // Certificate Table
	IMAGE_DIRECTORY_ENTRY_BASERELOC      = 5  // Base Relocation Table
	IMAGE_DIRECTORY_ENTRY_DEBUG          = 6  // Debug
	IMAGE_DIRECTORY_ENTRY_ARCHITECTURE   = 7  // Architecture (reserved, must be 0)
	IMAGE_DIRECTORY_ENTRY_GLOBALPTR      = 8  // Global Pointer
	IMAGE_DIRECTORY_ENTRY_TLS            = 9  // TLS Table
	IMAGE_DIRECTORY_ENTRY_LOAD_CONFIG    = 10 // Load Config Table
	IMAGE_DIRECTORY_ENTRY_BOUND_IMPORT   = 11 // Bound Import
	IMAGE_DIRECTORY_ENTRY_IAT            = 12 // Import Address Table
	IMAGE_DIRECTORY_ENTRY_DELAY_IMPORT   = 13 // Delay Load Import Descriptors
	IMAGE_DIRECTORY_ENTRY_COM_DESCRIPTOR = 14 // CLR Runtime Header
	IMAGE_NUMBEROF_DIRECTORY_ENTRIES     = 16
)

// Section Characteristics (IMAGE_SCN_*)
const (
	IMAGE_SCN_TYPE_NO_PAD            = 0x00000008
	IMAGE_SCN_CNT_CODE               = 0x00000020
	IMAGE_SCN_CNT_INITIALIZED_DATA   = 0x00000040
	IMAGE_SCN_CNT_UNINITIALIZED_DATA = 0x00000080
	IMAGE_SCN_LNK_OTHER              = 0x00000100
	IMAGE_SCN_LNK_INFO               = 0x00000200
	IMAGE_SCN_LNK_REMOVE             = 0x00000800
	IMAGE_SCN_LNK_COMDAT             = 0x00001000
	IMAGE_SCN_GPREL                  = 0x00008000
	IMAGE_SCN_MEM_PURGEABLE          = 0x00020000
	IMAGE_SCN_MEM_16BIT              = 0x00020000
	IMAGE_SCN_MEM_LOCKED             = 0x00040000
	IMAGE_SCN_MEM_PRELOAD            = 0x00080000
	IMAGE_SCN_ALIGN_1BYTES           = 0x00100000
	IMAGE_SCN_ALIGN_2BYTES           = 0x00200000
	IMAGE_SCN_ALIGN_4BYTES           = 0x00300000
	IMAGE_SCN_ALIGN_8BYTES           = 0x00400000
	IMAGE_SCN_ALIGN_16BYTES          = 0x00500000
	IMAGE_SCN_ALIGN_32BYTES          = 0x00600000
	IMAGE_SCN_ALIGN_64BYTES          = 0x00700000
	IMAGE_SCN_ALIGN_128BYTES         = 0x00800000
	IMAGE_SCN_ALIGN_256BYTES         = 0x00900000
	IMAGE_SCN_ALIGN_512BYTES         = 0x00A00000
	IMAGE_SCN_ALIGN_1024BYTES        = 0x00B00000
	IMAGE_SCN_ALIGN_2048BYTES        = 0x00C00000
	IMAGE_SCN_ALIGN_4096BYTES        = 0x00D00000
	IMAGE_SCN_ALIGN_8192BYTES        = 0x00E00000
	IMAGE_SCN_LNK_NRELOC_OVFL        = 0x01000000
	IMAGE_SCN_MEM_DISCARDABLE        = 0x02000000
	IMAGE_SCN_MEM_NOT_CACHED         = 0x04000000
	IMAGE_SCN_MEM_NOT_PAGED          = 0x08000000
	IMAGE_SCN_MEM_SHARED             = 0x10000000
	IMAGE_SCN_MEM_EXECUTE            = 0x20000000
	IMAGE_SCN_MEM_READ               = 0x40000000
	IMAGE_SCN_MEM_WRITE              = 0x80000000
)

// Base Relocation Types (IMAGE_REL_BASED_*)
const (
	IMAGE_REL_BASED_ABSOLUTE           = 0
	IMAGE_REL_BASED_HIGH               = 1
	IMAGE_REL_BASED_LOW                = 2
	IMAGE_REL_BASED_HIGHLOW            = 3
	IMAGE_REL_BASED_HIGHADJ            = 4
	IMAGE_REL_BASED_MIPS_JMPADDR       = 5
	IMAGE_REL_BASED_ARM_MOV32          = 5
	IMAGE_REL_BASED_RISCV_HIGH20       = 5
	IMAGE_REL_BASED_THUMB_MOV32        = 7
	IMAGE_REL_BASED_RISCV_LOW12I       = 7
	IMAGE_REL_BASED_RISCV_LOW12S       = 8
	IMAGE_REL_BASED_LOONGARCH32_MARK_LA = 8
	IMAGE_REL_BASED_LOONGARCH64_MARK_LA = 8
	IMAGE_REL_BASED_MIPS_JMPADDR16     = 9
	IMAGE_REL_BASED_DIR64              = 10
)

// Debug Types (IMAGE_DEBUG_TYPE_*)
const (
	IMAGE_DEBUG_TYPE_UNKNOWN       = 0
	IMAGE_DEBUG_TYPE_COFF          = 1
	IMAGE_DEBUG_TYPE_CODEVIEW      = 2
	IMAGE_DEBUG_TYPE_FPO           = 3
	IMAGE_DEBUG_TYPE_MISC          = 4
	IMAGE_DEBUG_TYPE_EXCEPTION     = 5
	IMAGE_DEBUG_TYPE_FIXUP         = 6
	IMAGE_DEBUG_TYPE_OMAP_TO_SRC   = 7
	IMAGE_DEBUG_TYPE_OMAP_FROM_SRC = 8
	IMAGE_DEBUG_TYPE_BORLAND       = 9
	IMAGE_DEBUG_TYPE_RESERVED10    = 10
	IMAGE_DEBUG_TYPE_CLSID         = 11
	IMAGE_DEBUG_TYPE_REPRO         = 16
	IMAGE_DEBUG_TYPE_EMBEDDED_PDB  = 17
	IMAGE_DEBUG_TYPE_PDBCHECKSUM   = 19
	IMAGE_DEBUG_TYPE_EX_DLLCHARACTERISTICS = 20
)

// COFF Symbol Section Number special values (IMAGE_SYM_*)
const (
	IMAGE_SYM_UNDEFINED = 0  // Symbol is undefined or common
	IMAGE_SYM_ABSOLUTE  = -1 // Symbol has an absolute value
	IMAGE_SYM_DEBUG     = -2 // Symbol is a debugging entry
)

// COFF Symbol Type - Base Type (low byte of Type field)
const (
	IMAGE_SYM_TYPE_NULL   = 0  // No type
	IMAGE_SYM_TYPE_VOID   = 1  // Void
	IMAGE_SYM_TYPE_CHAR   = 2  // Character
	IMAGE_SYM_TYPE_SHORT  = 3  // Short integer
	IMAGE_SYM_TYPE_INT    = 4  // Integer
	IMAGE_SYM_TYPE_LONG   = 5  // Long integer
	IMAGE_SYM_TYPE_FLOAT  = 6  // Float
	IMAGE_SYM_TYPE_DOUBLE = 7  // Double
	IMAGE_SYM_TYPE_STRUCT = 8  // Structure
	IMAGE_SYM_TYPE_UNION  = 9  // Union
	IMAGE_SYM_TYPE_ENUM   = 10 // Enumeration
	IMAGE_SYM_TYPE_MOE    = 11 // Member of enumeration
	IMAGE_SYM_TYPE_BYTE   = 12 // Byte
	IMAGE_SYM_TYPE_WORD   = 13 // Word
	IMAGE_SYM_TYPE_UINT   = 14 // Unsigned integer
	IMAGE_SYM_TYPE_DWORD  = 15 // Double word
)

// COFF Symbol Type - Derived Type (high byte of Type field)
const (
	IMAGE_SYM_DTYPE_NULL     = 0 // No derived type
	IMAGE_SYM_DTYPE_POINTER  = 1 // Pointer
	IMAGE_SYM_DTYPE_FUNCTION = 2 // Function
	IMAGE_SYM_DTYPE_ARRAY    = 3 // Array
)

// COFF Symbol Storage Class (IMAGE_SYM_CLASS_*)
const (
	IMAGE_SYM_CLASS_END_OF_FUNCTION  = 0xFF // -1 as unsigned
	IMAGE_SYM_CLASS_NULL             = 0
	IMAGE_SYM_CLASS_AUTOMATIC        = 1
	IMAGE_SYM_CLASS_EXTERNAL         = 2
	IMAGE_SYM_CLASS_STATIC           = 3
	IMAGE_SYM_CLASS_REGISTER         = 4
	IMAGE_SYM_CLASS_EXTERNAL_DEF     = 5
	IMAGE_SYM_CLASS_LABEL            = 6
	IMAGE_SYM_CLASS_UNDEFINED_LABEL  = 7
	IMAGE_SYM_CLASS_MEMBER_OF_STRUCT = 8
	IMAGE_SYM_CLASS_ARGUMENT         = 9
	IMAGE_SYM_CLASS_STRUCT_TAG       = 10
	IMAGE_SYM_CLASS_MEMBER_OF_UNION  = 11
	IMAGE_SYM_CLASS_UNION_TAG        = 12
	IMAGE_SYM_CLASS_TYPE_DEFINITION  = 13
	IMAGE_SYM_CLASS_UNDEFINED_STATIC = 14
	IMAGE_SYM_CLASS_ENUM_TAG         = 15
	IMAGE_SYM_CLASS_MEMBER_OF_ENUM   = 16
	IMAGE_SYM_CLASS_REGISTER_PARAM   = 17
	IMAGE_SYM_CLASS_BIT_FIELD        = 18
	IMAGE_SYM_CLASS_BLOCK            = 100
	IMAGE_SYM_CLASS_FUNCTION         = 101
	IMAGE_SYM_CLASS_END_OF_STRUCT    = 102
	IMAGE_SYM_CLASS_FILE             = 103
	IMAGE_SYM_CLASS_SECTION          = 104
	IMAGE_SYM_CLASS_WEAK_EXTERNAL    = 105
	IMAGE_SYM_CLASS_CLR_TOKEN        = 107
)

// MachineString returns a human-readable string for a machine type.
func MachineString(machine uint16) string {
	switch machine {
	case IMAGE_FILE_MACHINE_UNKNOWN:
		return "unknown"
	case IMAGE_FILE_MACHINE_I386:
		return "i386"
	case IMAGE_FILE_MACHINE_AMD64:
		return "x86_64"
	case IMAGE_FILE_MACHINE_ARM:
		return "arm"
	case IMAGE_FILE_MACHINE_ARM64:
		return "arm64"
	case IMAGE_FILE_MACHINE_ARM64EC:
		return "arm64ec"
	case IMAGE_FILE_MACHINE_ARM64X:
		return "arm64x"
	case IMAGE_FILE_MACHINE_ARMNT:
		return "armnt"
	case IMAGE_FILE_MACHINE_IA64:
		return "ia64"
	case IMAGE_FILE_MACHINE_RISCV32:
		return "riscv32"
	case IMAGE_FILE_MACHINE_RISCV64:
		return "riscv64"
	case IMAGE_FILE_MACHINE_RISCV128:
		return "riscv128"
	case IMAGE_FILE_MACHINE_LOONGARCH32:
		return "loongarch32"
	case IMAGE_FILE_MACHINE_LOONGARCH64:
		return "loongarch64"
	case IMAGE_FILE_MACHINE_POWERPC:
		return "powerpc"
	case IMAGE_FILE_MACHINE_POWERPCFP:
		return "powerpcfp"
	case IMAGE_FILE_MACHINE_MIPS16:
		return "mips16"
	case IMAGE_FILE_MACHINE_MIPSFPU:
		return "mipsfpu"
	case IMAGE_FILE_MACHINE_MIPSFPU16:
		return "mipsfpu16"
	case IMAGE_FILE_MACHINE_R3000:
		return "r3000"
	case IMAGE_FILE_MACHINE_R4000:
		return "r4000"
	case IMAGE_FILE_MACHINE_R10000:
		return "r10000"
	case IMAGE_FILE_MACHINE_SH3:
		return "sh3"
	case IMAGE_FILE_MACHINE_SH3DSP:
		return "sh3dsp"
	case IMAGE_FILE_MACHINE_SH4:
		return "sh4"
	case IMAGE_FILE_MACHINE_SH5:
		return "sh5"
	case IMAGE_FILE_MACHINE_THUMB:
		return "thumb"
	case IMAGE_FILE_MACHINE_EBC:
		return "ebc"
	case IMAGE_FILE_MACHINE_ALPHA:
		return "alpha"
	case IMAGE_FILE_MACHINE_ALPHA64:
		return "alpha64"
	case IMAGE_FILE_MACHINE_M32R:
		return "m32r"
	default:
		return "unknown"
	}
}

// SubsystemString returns a human-readable string for a subsystem value.
func SubsystemString(subsystem uint16) string {
	switch subsystem {
	case IMAGE_SUBSYSTEM_UNKNOWN:
		return "unknown"
	case IMAGE_SUBSYSTEM_NATIVE:
		return "native"
	case IMAGE_SUBSYSTEM_WINDOWS_GUI:
		return "windows_gui"
	case IMAGE_SUBSYSTEM_WINDOWS_CUI:
		return "windows_cui"
	case IMAGE_SUBSYSTEM_OS2_CUI:
		return "os2_cui"
	case IMAGE_SUBSYSTEM_POSIX_CUI:
		return "posix_cui"
	case IMAGE_SUBSYSTEM_NATIVE_WINDOWS:
		return "native_windows"
	case IMAGE_SUBSYSTEM_WINDOWS_CE_GUI:
		return "windows_ce_gui"
	case IMAGE_SUBSYSTEM_EFI_APPLICATION:
		return "efi_application"
	case IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER:
		return "efi_boot_service_driver"
	case IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER:
		return "efi_runtime_driver"
	case IMAGE_SUBSYSTEM_EFI_ROM:
		return "efi_rom"
	case IMAGE_SUBSYSTEM_XBOX:
		return "xbox"
	case IMAGE_SUBSYSTEM_WINDOWS_BOOT_APPLICATION:
		return "windows_boot_application"
	default:
		return "unknown"
	}
}
