package sessiond

import (
	"net"

	"github.com/SeungKang/memshonk/internal/cstlv"
)

// stdSplitterWriter copies stderr or stdout to an underlying net.Conn.
type stdSplitterWriter struct {
	conn     net.Conn
	isStderr bool
}

func (o stdSplitterWriter) Write(b []byte) (int, error) {
	msg := cstlv.CSTLV{
		Val: b,
	}

	if o.isStderr {
		msg.Chan = 0x01
	}

	_, err := o.conn.Write(msg.AutoBytes())
	if err != nil {
		return 0, err
	}

	return len(b), nil
}

func newStdSplitterReader(conn net.Conn) stdSplitterReader {
	return stdSplitterReader{
		msgs: cstlv.NewParserFrom(conn),
	}
}

// stdSplitterReader splits out stderr and stdout data from
// messages generated by a stdSplitterWriter.
type stdSplitterReader struct {
	msgs *cstlv.Parser
}

func (o stdSplitterReader) next() (int, []byte, error) {
	if !o.msgs.Next() {
		return 0, nil, o.msgs.Err()
	}

	msg := o.msgs.Message()

	return int(msg.Chan), msg.Val, nil
}
