package shell

import (
	"bytes"
	"cmp"
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/SeungKang/memshonk/internal/apicompat"

	"mvdan.cc/sh/v3/expand"
	"mvdan.cc/sh/v3/interp"
	"mvdan.cc/sh/v3/syntax"
)

var (
	// errHandledBuiltin is returned when a builtin is
	// handled by this library. Since the sh library
	// does not provide a way to cancel its own builtin
	// code, we need to return a non-nil error to
	// force sh to skip its own logic. We also need
	// a way to check if said error was generated by
	// our custom code, which is what this error
	// object does.
	errHandledBuiltin = errors.New("builtin handled by custom handler")
)

// NewInterpreter creates a new shell interpreter.
func NewInterpreter(session apicompat.Session, cmdHandler *apicompat.CommandHandler) (*Interpreter, error) {
	i := &Interpreter{
		session: session,
		cmdHand: cmdHandler,
		parser:  syntax.NewParser(),
	}

	sio := session.IO()

	// Use an empty reader for stdin to avoid competing
	// with readline for input. Built-in commands don't
	// read from stdin, and external commands that need
	// stdin piping would require a different approach
	// (e.g., temporarily giving them exclusive access
	// to the terminal).
	emptyStdin := bytes.NewReader(nil)

	runner, err := interp.New(
		interp.StdIO(emptyStdin, sio.Stdout, sio.Stderr),
		interp.Env(expand.ListEnviron(session.SharedState().Vars.KeyValues(nil)...)),
		interp.CallHandler(i.builtinHandler),
		interp.ExecHandlers(i.execHandler),
	)
	if err != nil {
		return nil, fmt.Errorf("failed to create interpreter - %w", err)
	}

	i.runner = runner

	return i, nil
}

// Interpreter wraps mvdan/sh to provide shell interpretation with built-in
// command routing.
type Interpreter struct {
	session apicompat.Session
	cmdHand *apicompat.CommandHandler
	parser  *syntax.Parser
	runner  *interp.Runner
}

// builtinHandler overrides some broken builtins in the sh library.
func (o *Interpreter) builtinHandler(ctx context.Context, argv []string) ([]string, error) {
	switch argv[0] {
	case "cd":
		handlerCtx := interp.HandlerCtx(ctx)

		_, err := o.handleCd(handlerCtx, argv[1:])
		if err != nil {
			handlerCtx.Stderr.Write([]byte("cd: " + err.Error() + "\n"))
		}

		// TODO: The sh library does not allow us to safely
		// set the cwd, so idk... just let it run its "cd"
		// code I guess :/

		return argv, nil
	case "wait":
		// TODO: The sh library's "wait" implementation
		// seems to hang forever and also has hard-coded
		// panic code.
		return argv, errHandledBuiltin
	default:
		return argv, nil
	}
}

// handleCd exists because the sh library's cd does not provide any
// context as to why it failed.
//
// This function's code is based on code from:
// mvdan.cc/sh/v3/interp/builtin.go
func (o *Interpreter) handleCd(handlerCtx interp.HandlerContext, args []string) (string, error) {
	var dirPath string

	var out string

	switch len(args) {
	case 0:
		dirPath = o.runner.Env.Get("HOME").Str
	case 1:
		dirPath = args[0]

		// replicate the commonly implemented behavior of `cd -`
		// ref: https://www.man7.org/linux/man-pages/man1/cd.1p.html#OPERANDS
		if dirPath == "-" {
			dirPath = o.runner.Env.Get("OLDPWD").Str

			out = dirPath
		}
	default:
		return "", fmt.Errorf("usage: cd [dir]")
	}

	dirPath = cmp.Or(dirPath, ".")
	dirPath = absPath(handlerCtx.Dir, dirPath)

	info, err := os.Stat(dirPath)
	switch {
	case err != nil:
		return "", fmt.Errorf("failed to stat directory - %w",
			err)
	case !info.IsDir():
		return "", fmt.Errorf("path is not a directory: %q",
			dirPath)
	}

	err = hasPermissionToDir(dirPath)
	if err != nil {
		return "", fmt.Errorf("access denied to directory %q - %w",
			dirPath, err)
	}

	// TODO: From here, we let the sh library re-run its "cd"
	// code because there is no way for us to safely set the
	// cwd from here.

	//r.Dir = path
	//r.setVarString("OLDPWD", r.envGet("PWD"))
	//r.setVarString("PWD", path)

	return out, nil
}

// Copied from:
// mvdan.cc/sh/v3/interp/builtin.go
func absPath(dir, path string) string {
	if path == "" {
		return ""
	}
	if !filepath.IsAbs(path) {
		path = filepath.Join(dir, path)
	}
	return filepath.Clean(path) // TODO: this clean is likely unnecessary
}

// Execute parses and executes a shell command line.
func (o *Interpreter) Execute(ctx context.Context, line string) error {
	// Parse the input
	file, err := o.parser.Parse(strings.NewReader(line), "")
	if err != nil {
		return fmt.Errorf("parse error - %w", err)
	}

	return o.runner.Run(ctx, file)
}

// execHandler routes command execution to built-in commands
// or external programs.
func (o *Interpreter) execHandler(interp.ExecHandlerFunc) interp.ExecHandlerFunc {
	return func(ctx context.Context, argv []string) error {
		// interp.HandlerCtx is the prescribed mechanism
		// for accesing the stdin/out pipes managed by
		// the sh library.
		handlerCtx := interp.HandlerCtx(ctx)

		err := o.cmdHand.Run(ctx, apicompat.RunCommandConfig{
			Argv:   argv,
			Env:    execEnv(handlerCtx.Env),
			Cwd:    handlerCtx.Dir,
			Stdin:  handlerCtx.Stdin,
			Stdout: handlerCtx.Stdout,
			Stderr: handlerCtx.Stderr,
		})
		if err != nil {
			exitStatus, hasIt := err.HasExitStatus()
			if !hasIt {
				exitStatus = 1
			}

			return interp.NewExitStatus(exitStatus)
		}

		return nil
	}
}

// execEnv is a copy of the private function of the same name from
// mvdan.cc/sh/v3, interp/vars.go
func execEnv(env expand.Environ) []string {
	list := make([]string, 0, 64)
	env.Each(func(name string, vr expand.Variable) bool {
		if !vr.IsSet() {
			// If a variable is set globally but unset in the
			// runner, we need to ensure it's not part of the final
			// list. Seems like zeroing the element is enough.
			// This is a linear search, but this scenario should be
			// rare, and the number of variables shouldn't be large.
			for i, kv := range list {
				if strings.HasPrefix(kv, name+"=") {
					list[i] = ""
				}
			}
		}
		if vr.Exported && vr.Kind == expand.String {
			list = append(list, name+"="+vr.String())
		}
		return true
	})
	return list
}
